# Generated by Django 3.2.9 on 2022-03-25 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_personalwatchlist_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='auctions',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='auctions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auctions_in_the_watchlist', to='auctions.auction'),
        ),
    ]
