# Generated by Django 3.2.9 on 2022-03-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_watchlist_auctions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='auctions',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='auctions',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='auctions_in_the_watchlist', to='auctions.Auction'),
        ),
    ]
